### ISSUE TITLE
How can we maximize reusability of compliance information?

### ISSUE THREAD

**Issue by afeld** [opencontrol/compliance-masonry#103]
*I am going to preface this issue by saying that I am still relatively to Masonry, and compliance in general. After starting to go through setting up Masonry for a web application the other day, I wanted to take a step back and brainstorm a bit about where (from a user's perspective) the underlying compliance data would ideally live.*

---

### cloud.gov

For cloud.gov, the compliance documentation is all being collected in https://github.com/18F/cg-compliance. That's fine, though what if another agency wanted to launch a system on AWS and get an ATO through Masonry? They could fork the repository, but they wouldn't benefit from any updates contributed upstream, unless they were diligent about checking for updates and merging. They would also probably want to delete the [`18F/`](https://github.com/18F/cg-compliance/tree/6d87ae551636e55920f4e6f2fbac6c4aa7aedeca/data/components/18F) directory since it doesn't apply to them, but this means that merging from upstream through Git becomes an even bigger headache.

From a quick glance, it seems like none of the information under [`AWS/`](https://github.com/18F/cg-compliance/tree/6d87ae551636e55920f4e6f2fbac6c4aa7aedeca/data/components/AWS) and [`CloudFoundry/`](https://github.com/18F/cg-compliance/tree/6d87ae551636e55920f4e6f2fbac6c4aa7aedeca/data/components/CloudFoundry) (minus the `implementation_status`) is (or needs to be) cloud.gov-specific.

### An application running on cloud.gov

As a second thought experiment, let's say an agency is launching a web application on cloud.gov. It would be great if their compliance information could be versioned along with their application code (in a repository they manage), but this would require copying the files from this repository into theirs, which would create a lot of clutter. They should only have to care about the information that's specific to their application. It would be great if the developer could say:

* "It's using cloud.gov, so inherit the cloud.gov controls," without needing to copy in all of the cloud.gov Masonry files (and keep them up-to-date).
* "This will be a FISMA Low application."
* "I am fulfilling SA-11 by using Brakeman on Code Climate," without needing to fill out the `references` to re-explain to Masonry what Code Climate is.

### A different platform

A third: suppose a hosting company wants to use Masonry to list their FedRAMP compliance information. It wouldn't make any sense for them to put their information in the "Compliance Masonry compatible repository for Cloud.gov" (cg-compliance), but they shouldn't have to maintain the `data/certifications/FedRAMP-*.yaml` files separately, either.

## Takeaways

A few overall themes here:

* How can we avoid duplicating compliance information? (that can get out of date living in two places)
* How can we allow projects to keep compliance information specific to their system in the repository of their choosing?
* How can we distinguish compliance information that is general-purpose versus that that is implementation-specific? Examples of the former:
    * The list of sub-components of Cloud Foundry
    * What controls make up FedRAMP Medium
    * Where to find information about Code Climate / Logentries / any other reusable "component"

## Suggestion

Short of supporting the reusable compliance data living _anywhere_, a good starting place might be to create a centralized "library" of `certifications` and `components` (e.g. "here is the canonical information about how EC2 fulfills NIST-800-53 SC-7"). A sketch of how that might work:

* `opencontrol/masonry-data` repository
    * `data/`
        * `certifications/`
            * `18f_open_data.yaml`
            * `gsa_fisma_low.yaml`
            * `fedramp_med.yaml`
        * `components/`
            * `aws/`
            * `cloud_foundry/`
            * `cloud_gov/`
                * `component.yaml`

                    ```yaml
                    inherits:
                    - aws
                    - cloud_foundry
                    ```
            * `code_climate/`
* `18F/C2` repository (i.e. an application)
    * `masonry/`
        * `system.yaml`

            ```yaml
            inherits:
            - cloud_gov
            verifications:
            - component: code_climate
              type: URL
              path: ...
            ```

The `masonry-data` could be pulled in by the `masonry` tool when run in the context of `C2/`, but doesn't need to be copied around by the user. Maybe that data gets packaged with the tool (a la [Homebrew](https://github.com/Homebrew/homebrew/tree/master/Library/Formula)) or is downloaded from elsewhere as part of `masonry docs` – whatever works.

---

Not sure if any of this makes sense...thoughts?

**Comment by mogul** [comment]
It makes sense and we're doing some things in `cg-compliance` with an eye toward more modular reuse, eg keeping the corpus of BDD step code alongside the controls themselves.  As it stands, the directory structure is pretty reasonably keeping things separate. It feels like this may be a case for submodules and many many small repositories

However, we're pretty far from the usability most existing authors would expect as it stands until we get a UI up, and relying on "advanced" git features will be a further barrier to entry. Also it may not matter as much where the YAML actually is if we provide a comfortable UI for assembling the pieces from a "bank".

**Comment by joshuamckenty** [comment]
Given that the central premise of open-control is to allow machine-readable compliance data to be driven thru CI/CD tools, I'm much more interested in the ways that example pipelines can assemble a _logically-separated and semantically valid_ set of modules (certifications, components, policies, etc) than I am in either CLI or UI tooling.

It's still *very* rough, but the interface to jinjame.py in https://github.com/opencontrol/example-pipelines (see the run_tests.sh example) is a simple way to combine YAML from several repos, and it's known to work within a concourse pipeline.

**Comment by joshuamckenty** [comment]
A second argument for submodules - any specific SSP will need to rely on the set of certifications and components data at a _specific version_ (which matches the version of the components they're running), and submodules are a tidy way to do that.

**Comment by joshuamckenty** [comment]
One last thought -

Eventually, I think we *have* to start using YAML tags to include version data in the various certification and component files. So having the raw certification YAML in a repo of its' own would allow us to post-process it (attaching appropriate version headers), and then "publish" it into a GitHub release.

Semver could be used to track both open-control-based versioning (for schema changes or typos), and upstream versioning (such as an updated version of FedRAMP).

**Comment by geramirez** [comment]
@aiden So, I agree with most of your thoughts. Components should absolutely be organized in way that would allow users to choose their components more easily. But, I’m not so sure that maintaining a system of inheritance is the best way. 

For example, if Cloud.gov stops using Code Climate you’ll end up with a missing reference your C2 documents. I think we should aim for systems and components as self-contained as possible to facilitate stack changes. 

Maybe this has been suggested already but… pip, npm, godeps, etc. all use local files that point to “dependencies” could we do the same with compliance dependencies? 

```json
{
    "name": "C2",
     "dependencies”: {
         “https://github.com/18F/cg-compliance/”: “0.3”,
          …
}
```

@joshuamckenty, I’m not sure this would solve the CI/CD problem, but I think it would make it easier for devs to build their own compliance docs and it would be a way of versioning compliance docs for components.

**Comment by geramirez** [comment]
Here is a more complete version of what a `compliance manager package tool` would look like. 
Two of the largest pain points in the current compliance process are:
1. Using existing compliance documentation in new projects, (Currently, projects can be forked or cloned..)
2. Versioning, basically we have none. 

I think the solution for these pain points would be to create a compliance manager package tool. This tool, which could be added to Compliance Masonry or be implemented individually and would have: 

## 1.  ssp.yaml/ssp.json
The ssp.yaml/ssp.json file would contain dependencies for building the documentation. Dependencies would be versioned and split into 3 categories 
systems - systems like aws, 18f, or CF
standards - specific versions on NIST or PCI
certifications - custom certifications yamls like LATO or FedRAMP

```
name: New Project  
authors: 18F delivery team  
date_published: date  
type: documentation # also could have standards, certifications  
version: 2.0  
local_path: Application  
dependencies:  
  systems:  
    CloudGov: 1.4  
  standards:  
    NIST-500-83: v20140101  
   certifications:  
     FedRAMP-med: v20120101  
```

## 2. Specific file structure
```
application/ --- for the application somebody is working on
   system.yaml
   components/ etc..
opencontrols/  --- the dependencies 
  - systems/
    CloudGov/
      system.yaml
      components/ etc..
  - standards/
      NIST-500-83.yaml
  - certifications
      LATO-GSA.yaml
```
## 3. A get method
This method downloads all the dependencies into a folder called opencontrols

## 4. A docs method
Uses the dependencies in opencontrols which include systems, standards, certifications IN ADDITION TO the local systems folder to generate documentation.

## 5. Init Method
A method that walks a user through starting documentation, a standards, or certification

**Comment by afeld** [comment]
I think a package manager would make a lot of sense in the longer term, but wonder what shortcuts we could take in the meantime to distribute them, e.g. using

* The `masonry-data` idea suggested at the top
* Submodules
* Python Packages

**Comment by afeld** [comment]
With [Schema V2](https://github.com/opencontrol/schemas), I think we can call this case closed!
