### ISSUE TITLE
Extend the templater to handle individual fields instead of the entire controls.

### ISSUE THREAD

**Issue by DavidEBest** [opencontrol/compliance-masonry#132]
For more details view: https://github.com/opencontrol/compliance-masonry/pull/117

TODO:  
Before creating a FedRAMP template we need to make sure that FedRAMP will accept our output. contact: Bridget from FedRAMP

Right now control data is exported in a way that might not be up to their specific standards and before putting in hours of work to build a template it might be better to do some user research.

For example, Compliance Masonry docs do no split the control descriptions; however, the FedRAMP SSP might. There may be other formatting issues that we don't know about without more communication.

**Comment by afeld** [comment]
Completed by https://github.com/opencontrol/compliance-masonry/pull/160. We can open issues for more specific templating needs as they come up.
