### ISSUE TITLE
As a user, I'd like to get output from CM in json so that I can integrate it into other tools.

### ISSUE THREAD

**Issue by DavidEBest** [opencontrol/compliance-masonry#134]
To ease integration into the compliance toolkit, compliance masonry should support optional machine readable output for end products.

Right now, the only end product that we are concerned with is the gap analysis, but this should be handled in a general enough way that additional commands could be added.

**Comment by afeld** [comment]
The information is already in a machine-readable format (YAML)...let's open up more specific issues for where JSON output should be available as needs arise.
