### ISSUE TITLE
Error running `compliance-masonry get`

### ISSUE THREAD

**Issue by afeld** [opencontrol/compliance-masonry#147]
From @jacobian in https://github.com/18F/cg-compliance/issues/66:

> Working on https://github.com/18F/bug-bounty, and I'm getting this error:
> 
> ```
> $ compliance-masonry get
> Compliance Dependencies InstalledDEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
> ```
> 
> The `opencontrols` dir does still get created, and appears (?) to be complete, so perhaps this is just noise?

**Comment by jcscottiii** [comment]
@jacobian was this error from the stock `cg-compliance` opencontrol.yml ?

**Comment by jacobian** [comment]
@jcscottiii I think so? I installed it with `go get github.com/opencontrol/compliance-masonry`, following the instructions.

**Comment by jacobian** [comment]
Er, wait, "stock cg-compliance opencontrol.yml" I'm not sure what that means. I was following the instructions here: https://github.com/18F/cg-compliance#starting-ato-documentation-for-cloudgov-applications

**Comment by afeld** [comment]
@jacobian Can you try downloading the Masonry binary from https://github.com/opencontrol/compliance-masonry/releases and seeing if using that gives you the same error?

**Comment by openprivacy** [comment]
I got the same "error" (running Arch GNU/Linux) and it appears it's not an error, just a spurious message that will be fixed in the next release: https://github.com/gogits/gogs/issues/3045

**Comment by afeld** [comment]
Confirmed this is something that needs to be fixed on our side, since we're using the old `app.Action` signature in many places.

https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
