### ISSUE TITLE
As a user, I would like to be able to use multiple versions of component.yaml

### ISSUE THREAD

**Issue by jcscottiii** [opencontrol/compliance-masonry#152]

**Comment by geramirez** [comment]
ugg, totally regretting not setting up semver support for the component.yaml like you (@jcscottiii) did for the opencontrol.yaml  is it too late for a refactor? Either way looks like you worked it out. :100:

**Comment by joshuamckenty** [comment]
It's never too late to go to Semver.

**Comment by geramirez** [comment]
ah, I spoke too soon, just read #151

**Comment by jcscottiii** [comment]
yep! it's coming https://github.com/opencontrol/compliance-masonry/pull/158 (that's the smaller patch)

**Comment by afeld** [comment]
Fixed by https://github.com/opencontrol/compliance-masonry/pull/157, yeah?

**Comment by afeld** [comment]
Pretty sure the answer is "yes"...please re-open if this is not the case.
