### ISSUE TITLE
As a developer, I should be able to use compile-time flags to create a version

### ISSUE THREAD

**Issue by jcscottiii** [opencontrol/compliance-masonry#170]
Instead of creating a commit for just bumping the version in the code, you can use Go's `ldflags` to input a version at compile time. (You already have to bump the version in .goxc.json)

Search for it here: https://github.com/laher/goxc

http://www.atatus.com/blog/golang-auto-build-versioning/

Not sure but I think goxc can take PackageVersion and add it to ldflags automatically.

**Comment by shawndwells** [comment]
resolved through https://github.com/opencontrol/compliance-masonry/pull/304
