### ISSUE TITLE
Why was the switch made from Python to Go?

### ISSUE THREAD

**Issue by gregelin** [opencontrol/compliance-masonry#176]
Was looking through the issues trying to find the reasoning for switching from python to go. Didn't find it. What was the reasoning?

**Comment by jcscottiii** [comment]
We probably should move @geramirez's reasons from this repo https://github.com/opencontrol/compliance-masonry-go/issues/13 to here

**Comment by jcscottiii** [comment]
The tl;dr is due to:

1. many one-off developer issues
2. complex packaging vs a binary
3. size

**Comment by gregelin** [comment]
@jcscottiii Thanks for quick response and link to issue. Definitely should include here, in wiki...

**Comment by afeld** [comment]
I'd also add "easier to support cross-platform".

> Definitely should include here

I dunno, we could have a "Masonry history" page or something, but would anyone aside from the handful of people who have paid close attention to Masonry since then actually care?

**Comment by gregelin** [comment]
A "Masonry history" page would be useful. Also a roadmap.

Would others outside the current group of interested party care about Masonry history? This gets back to the roadmap. What is the aspiration of Compliance-Masonry, and in what time frame? 

Maybe the bigger question need is to have the group take a moment to define who the intended users are of OpenControl and Compliance-Masonry.

**Comment by openprivacy** [comment]
The history would be interesting to see the rationale for major changes, but less important that a roadmap. Would love to see more about the future of verifications, how they relate to controls and what happens when several tests are needed for a single control but only a few pass.

**Comment by afeld** [comment]
Yep, definitely agree about the forward-looking things. At least for 18F, we need to figure out what kind of time we are going to dedicate to Masonry in the near future, which would affect any sort of roadmap (or the timeline, at the very least).

I'd merge a pull request explaining the history, but I think pointing to past issues (including this one) and pull requests is sufficient for now.

**Comment by afeld** [comment]
Closing to keep the issue list actionable, but that isn't meant to stifle the discussion!

**Comment by joshuamckenty** [comment]
I still dream of OpenControl (possibly via Masonry) supporting multiple clients in multiple languages, with a common schema and a shared set of YAML files. 

In that regard, I’m keen to see our YAML files be useful and portable without explicit coupling to Masonry itself.

Of course, I realize that OSS is driven by PRs and not dreams.

**Comment by afeld** [comment]
If we are strict about enforcing the [schema versioning](https://github.com/opencontrol/schemas/issues/1), no reason clients couldn't be written in multiple languages!
