### ISSUE TITLE
Add explicit instructions on how to use control-masonry 

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#18]
Documentation should answer questions below
- [ ] What files does a person have to create (e.g., FISMA.yaml)
- [x] What files are generated by running scripts (e.g., what files change in the repository when you use it)?
- [x] How do you clone/fork/whatever and use control-masonry in your project?
- [ ] How do you add your own components, customize text for existing controls?

via @gregelin

**Comment by gregelin** [comment]
@ramirezg I would add to this:
- [ ] How to adjust jekyll templates and css

**Comment by afeld** [comment]
Closing as stale.
