### ISSUE TITLE
gitbook is not generating html

### ISSUE THREAD

**Issue by pburkholder** [opencontrol/compliance-masonry#182]
Steps to reproduce:

```
git clone https://github.com/pburkholder/freedonia-compliance.git
cd freedonia-compliance/
compliance-masonry get
compliance-masonry docs gitbook FredRAMP-low
cd exports && gitbook serve
```

Expect: 
```
── system_documentation
    ├── about-the-ssp.html
    ├── system-data.html
    └── system-description.html
```

Get:

```
└── system_documentation
    ├── about-the-ssp.md
    ├── system-data.md
    └── system-description.md
```

Why do I get markdown instead of html?

Thanks, Peter

**Comment by afeld** [comment]
This seems to be a gitbook issue: https://github.com/GitbookIO/gitbook/issues/81. Try adding a `SUMMARY.md` under `markdowns/` and linking to those pages.

**Comment by pburkholder** [comment]
Yep! That fixes it.  Thanks. I should've looked at the GitBoot docs, but now I know.

In the interests of DRY, might it be better not to have a README at all?

**Comment by afeld** [comment]
The README seems to generate this part:

![screen_shot_2016-06-24_at_10_50_08_am](https://cloud.githubusercontent.com/assets/86842/16341118/8a9eb790-39f9-11e6-8d1c-8191209a5019.png)

I don't personally know a ton about gitbook, but we should [document it](https://github.com/opencontrol/compliance-masonry/issues/183).

**Comment by afeld** [comment]
i.e. I'm going to leave it in [cg-compliance](https://github.com/18F/cg-compliance/tree/master/markdowns) for now, but it's not _strictly_ necessary for the gitbook to work.

**Comment by geramirez** [comment]
seems like more evidence for #153
