### ISSUE TITLE
Release 1.1.2 (1.2.0)?

### ISSUE THREAD

**Issue by pburkholder** [opencontrol/compliance-masonry#193]
Hi,

I'd like to have https://github.com/opencontrol/compliance-masonry/pull/192 so demos I have work. Could we get a release out soon? 

Thanks, Peter

**Comment by pburkholder** [comment]
I updated my repo at https://github.com/pburkholder/freedonia-compliance to require PR #192 (oops).

Could we get a release of masonry so my walk-through works? Thanks, Peter

**Comment by jcscottiii** [comment]
Merge https://github.com/opencontrol/compliance-masonry/pull/199 and I'll kick off the release!

**Comment by jcscottiii** [comment]
Also, could you put a short snippet of your patch so I can put in the release notes?

**Comment by jcscottiii** [comment]
fixed by #199
