### ISSUE TITLE
Render from CM directly into the FedRAMP .docx template

### ISSUE THREAD

**Issue by mogul** [opencontrol/compliance-masonry#198]
In order to generate output in exactly the template required for the FedRAMP process, we want a custom formatter for CM that understands specifics of the FedRAMP Word template.

**Acceptance Criteria**
- [x] There's a separate FedRAMP-rendering component that handles everything originally in CM - https://github.com/opencontrol/fedramp-templater
- [ ] The FedRAMP-rendering component can generate all (most?) of the Word doc from the OpenControl files
- [ ] Word and FedRAMP presentation logic doesn't exist in the Compliance Masonry repository - https://github.com/opencontrol/compliance-masonry/pull/210

**Comment by afeld** [comment]
I'm going to take a pass at splitting this up into smaller pieces.

**Comment by afeld** [comment]
Closing in favor of https://github.com/opencontrol/fedramp-templater.
