### ISSUE TITLE
CircleCI build failing

### ISSUE THREAD

**Issue by afeld** [opencontrol/compliance-masonry#208]
...on `master`, as of https://circleci.com/gh/opencontrol/compliance-masonry/241. Weirdly, the following commands work fine locally:

```bash
go build
go test -v $(glide nv)
```

**Comment by jcscottiii** [comment]
While the cache of CircleCI helps, this time it's the curse of the cache.

CircleCI will first bring back all the previous sources then it will override with the new source from the PR / push. However, in the case when files have been moved around, the old location of files will stay there so there's a conflict of things like 1) something already being in the name space or 2) the import paths no longer existing.

In either case, we need to build without the cache:
![image](https://cloud.githubusercontent.com/assets/7788930/17138031/53f392ac-530c-11e6-98bb-f2bef33dfcc4.png)

**Comment by jcscottiii** [comment]
I think we can tell CircleCI to build without the cache all the time. It won't take that much longer. There would need to be a edit to the circle.yml.. I think... Not sure

**Comment by afeld** [comment]
Iininteresting. Good to know!
