### ISSUE TITLE
move the "Masonry for the compliance literate" documentation in

### ISSUE THREAD

**Issue by afeld** [opencontrol/compliance-masonry#220]
Broken out from https://github.com/18F/cg-product/issues/253.

https://docs.google.com/document/d/1mNV7yzrorBF4YD9uIOr75KOPCrta8eMkk0Gf8edhyZs/edit

**Comment by afeld** [comment]
Not exactly sure of the best place for this to live...the README is getting long enough that we might want to start splitting it out to different Markdown files under a `docs/` folder or something (or maybe move documentation to [the website](http://open-control.org/))...that is a whole other can of worms though, and thus should probably be its own issue ("content strategy for Masonry/OpenControl").

/cc @brittag

**Comment by brittag** [comment]
I'd do something simple for now - make a `docs/` folder, put a .md file in it, link to that from the README. Then when we have a chance to talk about overall content strategy for Masonry/OpenControl, we can figure out where best to put it!
