### ISSUE TITLE
File structure?

### ISSUE THREAD

**Issue by DruidSmith** [opencontrol/compliance-masonry#223]
I was able to successfully install Go 1.6 and folllowing the directions provided, https://github.com/opencontrol/compliance-masonry ran go get and it successfully created compliance-masonry.exe in my specified %GOPATH% folder, C:\Users\DSmith04\Documents\GO_Work\bin

I then created a directory, C:\Users\DSmith04\Documents\GO_Work\EDAP_ATO and created an opencontrol.yaml file containing the sample content here: https://github.com/opencontrol/schemas#opencontrolyaml

Then tried executing it, `C:\Users\DSmith04\Documents\GO_Work\EDAP_ATO>%GOPATH%\bin\compliance-masonry get `

and it returns _No data to parse_

The documentation needs clearer information on where data needs to be located in order for the app to find it.

**Comment by jcscottiii** [comment]
@DruidSmith hmm could you try to clone this repo (https://github.com/opencontrol/freedonia-compliance) and running the `get` command while in the root of that folder?

**Comment by DruidSmith** [comment]
That worked, thanks!

**Comment by jcscottiii** [comment]
Great! I think it's because the data in the opencontrol.yaml in schemas lacks the local component data that you need to create on your own. But to be more clear about our errors, we are currently tracking #168
