### ISSUE TITLE
Standard control type should include a "Description" field

### ISSUE THREAD

**Issue by anweiss** [opencontrol/compliance-masonry#242]
The [`Control`](https://github.com/opencontrol/compliance-masonry/blob/abd21ce19eabf2cfccb5ec39b92ec45b747e2c23/lib/standards/versions/1_0_0/standard.go#L11) type should parse a field called "Description" that includes a short description of the control/customer responsibility.

e.g.

```go
type Control struct {
	Family      string `yaml:"family" json:"family"`
	Name        string `yaml:"name" json:"name"`
	Description string `yaml:"description" json:"description"`
}
```

This relates to https://github.com/opencontrol/schemas/issues/54

**Comment by jcscottiii** [comment]
Issue moved to [opencontrol/schemas #60](https://github.com/opencontrol/schemas/issues/60) via [**ZenHub**](https://www.zenhub.com/)
