### ISSUE TITLE
compliance-masonry:  in slim docker image

### ISSUE THREAD

**Issue by sometheycallme** [opencontrol/compliance-masonry#244]
@pburkholder 

FYI - If it's useful, I've toyed with a rudimentary docker image for CM with minimum deps installed.  WIP.  working on gitbook.  little mods and playing with the project structure, kwalify, book.json etc.  May add kwalify to the harness.

This pattern could be used for the freedonia project.

https://hub.docker.com/r/sometheycallme/compliance/
https://github.com/cleanerbot/compliance

-Tim

**Comment by anweiss** [comment]
This is awesome!
