### ISSUE TITLE
exe files are missing in the Windows Builds.

### ISSUE THREAD

**Issue by madhugilla** [opencontrol/compliance-masonry#248]
Hello All,

Both 64bit and 32 bit  .Zip install files from the link https://github.com/opencontrol/compliance-masonry/blob/master/docs/install.md are missing the executable.

Changing the extension to .exe  dint help either.

Can you please share the latest .

Thanks -Madhu

**Comment by anweiss** [comment]
hey @madhugilla ... just tested this and both of the Windows .zip files do indeed contain the `compliance-masonry.exe` executables.

https://github.com/opencontrol/compliance-masonry/releases/download/v1.1.2/compliance-masonry_1.1.2_windows_386.zip

https://github.com/opencontrol/compliance-masonry/releases/download/v1.1.2/compliance-masonry_1.1.2_windows_amd64.zip

**Comment by afeld** [comment]
Yep, I'm seeing them too... closing, though feel free to comment/reopen if there is indeed an issue!
