### ISSUE TITLE
RPM and Debian packaging for compliance-masonry?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/compliance-masonry#255]
Out of curiosity, why isn't compliance-masonry packaged for Red Hat/CentOS EPEL and Ubuntu? Has this been discussed before?

**Comment by afeld** [comment]
No, I don't think it has come up. It wouldn't be hard to do so, since it's simply a binary.

**Comment by anweiss** [comment]
[Bintary](https://bintray.com/) maybe?

**Comment by shawndwells** [comment]
To be more clear, why not package it as part of the distribution itself?

**Comment by afeld** [comment]
@shawndwells As a GitHub Release, you mean? Certainly could. Pull requests welcome with instructions/script(s) to do so 😉

**Comment by shawndwells** [comment]
From a RHEL/CentOS VM, I want to ``yum install compliance-masonry``, and have that pull from official(ish) repos like [EPEL](https://fedoraproject.org/wiki/EPEL) instead of having people downloading things from the internet.

Have been tinkering with ways to combine OpenSCAP (for compliance testing) and OpenControls (for ATO paperwork) into a single build system. To make that successful for end-customers, need to have all the tools installable natively.

**Comment by shawndwells** [comment]
I'll make a PR and we can move the discussion and tinkering there.
