### ISSUE TITLE
Tag and release master (post 1.1.2)?

### ISSUE THREAD

**Issue by phillbaker** [opencontrol/compliance-masonry#264]
Hello and thanks for all of your hard work on compliance-masonry - it's a great idea.

I wanted to follow up on the comment in https://github.com/opencontrol/compliance-masonry/issues/239 which mentioned tagging/releasing a new version - there's some great code on master that would be great to get officially tagged and released, is there any timeline for publishing a new release? 

(We also use a homebrew recipe which pulls from the releases, which would benefit from a release.)

**Comment by rogeruiz** [comment]
I found this too, and it seems like we'll possibly just need to modify where these deps are. but you're right this certainly complicates things.

https://github.com/opencontrol/compliance-masonry/pull/272

**Comment by shawndwells** [comment]
@rogeruiz you just did a rebuild... any secret to where these can be found? Technically I have them on my primary dev machine, and could copy things around... but seems overly hackish.

**Comment by rogeruiz** [comment]
this is what I relied on as well. I tried first to build the project from source, but ran into the same problems you mentioned.

**Comment by shawndwells** [comment]
Given the recent build system updates from @redhatrises (thank you!!), new release can easily be created. Closing this issue. Thanks again @rogeruiz for creating the releases in April.
