### ISSUE TITLE
Can you delete pre-release v1.1.3 for me?

### ISSUE THREAD

**Issue by andybrucenet** [opencontrol/compliance-masonry#266]
I created release v1.1.3 inadvertently in the opencontrol/compliance-masonry repo.

Although my github ID had the privileges to create the release, I do not seem to have the privileges to delete it.

Can you please delete this entire release for me?

Thanks,
Andy

**Comment by jcscottiii** [comment]
done

**Comment by andybrucenet** [comment]
Thanks! Made sure that publish works to my own repo for now :)
