### ISSUE TITLE
Standards Documentation 

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#27]
Any help on documenting (or auto generating) the [standards yamls](https://github.com/18F/control-masonry/tree/master/src/templates/standards/) would be welcome. 

We currently have some NIST controls, but we could use the rest and other standards.

**Comment by Gergues** [comment]
@geramirez  Are you referring to FedRAMP ?
can you list the standards that might be needed

PS: the link for the standards changed to 
https://github.com/18F/control-masonry/tree/master/src/templates/standards/

**Comment by geramirez** [comment]
@Gergues for standards we have NIST documented but we could always use more documentation possibly for PCI.  

We have FedRAMP listed under certifications because it pulls from standards like NIST. [We also need helping documenting those](https://github.com/18F/control-masonry/issues/28). So far we have FedRAMP-low and moderate, but the data might need some cleaning and accuracy checks. 

Also thanks for pointing out the broken link.

**Comment by mogul** [comment]
Also HIPAA
