### ISSUE TITLE
go-utils/ufs dependency not found

### ISSUE THREAD

**Issue by gbrunett** [opencontrol/compliance-masonry#270]
Please forgive the newbie question., but is anyone else getting this error?  Is there a workaround or fix available?

$ go get github.com/opencontrol/compliance-masonry
# cd .; git clone https://github.com/go-utils/ufs /usr/local/bin/src/github.com/go-utils/ufs
Cloning into '/usr/local/bin/src/github.com/go-utils/ufs'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/go-utils/ufs: exit status 128

Any guidance would be greatly appreciated.

**Comment by jamesrenfro** [comment]
I'm seeing the same error - it seems that ufs might be a private repo.

**Comment by jcscottiii** [comment]
it used to be a public repo. seems like they removed it / made it private. need to move to another library that abstracts file system operations. maybe something like: https://github.com/spf13/afero

**Comment by afeld** [comment]
Fixed by #272. Sorry for the delay!
