### ISSUE TITLE
MacOS Version of compliance-masonry Segfaults

### ISSUE THREAD

**Issue by twright-0x1** [opencontrol/compliance-masonry#271]
Upon downloading and running the compliance-masonry executable for Mac (with and without any command line parameters), I see only:

  Segmentation fault: 11

I'm using the latest MacOS High Sierra (10.13.2).

**Comment by tobybot11** [comment]
I have the same issue.

# compliance-masonry  -h
Segmentation fault: 11

**Comment by shawndwells** [comment]
Bump.

@jcscottiii is compliance-masonry still being maintained?

**Comment by mogul** [comment]
@jcscottiii left our organization and we're not able to put much attention into compliance-masonry right now. However, I'll see if I can wrangle someone to look into this...

**Comment by rogeruiz** [comment]
[compliance-masonry_1.1.2_darwin_amd64.zip](https://github.com/opencontrol/compliance-masonry/files/1877241/compliance-masonry_1.1.2_darwin_amd64.zip) :cd:
[compliance-masonry_1.1.2_darwin_386.zip](https://github.com/opencontrol/compliance-masonry/files/1877242/compliance-masonry_1.1.2_darwin_386.zip) 💾 

@twright-0x1 and @tobybot11 and @shawndwells can y'all give this a try? I recompiled the binaries using `go version go1.10 darwin/amd64` and I'm getting output without a segfault.

```shell
~/Developer/golang/src/github.com/opencontrol/compliance-masonry  tags/v1.1.2 
$> ./compliance-masonry_1.1.2_darwin_amd64/compliance-masonry --help
NAME:
   Compliance Masonry - Open Control CLI Tool

USAGE:
   compliance-masonry [global options] command [command options] [arguments...]

VERSION:
   1.1.2

COMMANDS:
     get, g   Install compliance dependencies
     docs, d  Create Documentation
     diff, d  Compute Gap Analysis
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --verbose      Indicates whether to run the command with verbosity.
   --help, -h     show help
   --version, -v  print the version
```

**Comment by shawndwells** [comment]
Works for me! Thank you!

**Comment by rogeruiz** [comment]
Alrighty, that's good enough for me. I have a copy of the old binaries I'll put here in case anyone still needs them, but for now we'll close this.

[OLD_compliance-masonry_1.1.2_darwin_386.zip](https://github.com/opencontrol/compliance-masonry/files/1877273/OLD_compliance-masonry_1.1.2_darwin_386.zip)
[OLD_compliance-masonry_1.1.2_darwin_amd64.zip](https://github.com/opencontrol/compliance-masonry/files/1877274/OLD_compliance-masonry_1.1.2_darwin_amd64.zip)

**Comment by shawndwells** [comment]
On 4/4/18 3:10 PM, Roger Steve Ruiz wrote:
>
> Alrighty, that's good enough for me. I have a copy of the old binaries 
> I'll put here in case anyone still needs them, but for now we'll close 
> this.
>
> OLD_compliance-masonry_1.1.2_darwin_386.zip 
> <https://github.com/opencontrol/compliance-masonry/files/1877273/OLD_compliance-masonry_1.1.2_darwin_386.zip>
> OLD_compliance-masonry_1.1.2_darwin_amd64.zip 
> <https://github.com/opencontrol/compliance-masonry/files/1877274/OLD_compliance-masonry_1.1.2_darwin_amd64.zip>
>
> —
>

Given this was a re-compile, could we create a new release (e.g. 1.1.3)?

**Comment by rogeruiz** [comment]
hmm. @shawndwells I could, but I have only recompiled the Mac version. I guess I could recompile all the binaries and make it a patch release.

**Comment by shawndwells** [comment]
On 4/4/18 3:12 PM, Roger Steve Ruiz wrote:
> hmm. @shawndwells <https://github.com/shawndwells> I could, but I have 
> only recompiled the Mac version. I guess I could recompile all the 
> binaries and make it a patch release.

How can I help?

**Comment by rogeruiz** [comment]
@shawndwells knowing which target binaries to compile for would help. Do we really need all of these? 

- compliance-masonry_1.1.2_amd64.deb
- compliance-masonry_1.1.2_armhf.deb
- compliance-masonry_1.1.2_darwin_386.zip
- compliance-masonry_1.1.2_darwin_amd64.zip
- compliance-masonry_1.1.2_i386.deb
- compliance-masonry_1.1.2_linux_386.tar.gz
- compliance-masonry_1.1.2_linux_amd64.tar.gz
- compliance-masonry_1.1.2_linux_arm.tar.gz
- compliance-masonry_1.1.2_windows_386.zip
- compliance-masonry_1.1.2_windows_amd64.zip

**Comment by rogeruiz** [comment]
@shawndwells alrighty, I just went ahead and used `goxc` even though it's no longer maintained. There is a new release with the recompiled binaries in there for version `1.1.3`. I also went ahead and replaced the updated binary in `1.1.2` to the old version as well.

**Comment by shawndwells** [comment]
On 4/4/18 3:41 PM, Roger Steve Ruiz wrote:
> @shawndwells <https://github.com/shawndwells> alrighty, I just went 
> ahead and used |goxc| even though it's no longer maintained. There is 
> a new release with the recompiled binaries in there for version 
> |1.1.3|. I also went ahead and replaced the updated binary in |1.1.2| 
> to the old version as well.

Thank you!!
