### ISSUE TITLE
Tools & Docs for package building

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/compliance-masonry#278]
Reminder/tracker to author docs around package building.

Originating from https://github.com/opencontrol/compliance-masonry/pull/277

Assigning to @redhatrises

**Comment by shawndwells** [comment]
well, I would if @redhatrises was part of the GH org =P . 

Assigning to self for now.

**Comment by redhatrises** [comment]
@shawndwells totally agree

**Comment by shawndwells** [comment]
Packages now autobuilt when tags are created. Resolving.

Thanks @redhatrises !
