### ISSUE TITLE
Certification Documentation

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#28]
Any help on documenting (or auto generating) the [certifications yamls](https://github.com/18F/control-masonry/tree/master/src/templates/certifications) would be welcome. 

We currently have dummy data for FISMA, but we would love to document requirements for FISMA Low, Moderate and High and any other certifications.

**Comment by afeld** [comment]
This seems out of scope for Masonry...closing for now.

**Comment by mogul** [comment]
Do you think the certifications belong in separate repositories?

**Comment by afeld** [comment]
No strong feelings from me.

**Comment by afeld** [comment]
Doesn't seem like a pressing issue.
