### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/compliance-masonry#293]
Two stale branches exist:

https://github.com/opencontrol/compliance-masonry/tree/include_files

and 

https://github.com/opencontrol/compliance-masonry/tree/bump-to-v1.1.3

Before removing them, @afeld and @jcscottiii are these branches ok to remove? They appear to be stale but wanted to double check!

**Comment by jcscottiii** [comment]
Yeah. We can remove those.

**Comment by jcscottiii** [comment]
I went ahead and removed them.

**Comment by shawndwells** [comment]
Sweet, thanks @jcscottiii!
