### ISSUE TITLE
Enable Travis CI or Org Admin permissions

### ISSUE THREAD

**Issue by redhatrises** [opencontrol/compliance-masonry#315]
https://travis-ci.org/opencontrol/compliance-masonry needs to be enabled for OSX dmg packaging.
@afeld can you do this? Or can you make @shawndwells and myself Org Admins to be able to do these things?

**Comment by shawndwells** [comment]
+cc @gregelin

**Comment by gregelin** [comment]
On it.

**Comment by gregelin** [comment]
https://travis-ci.org/opencontrol/compliance-masonry/ is now enabled for this repository. Let me know what else I can do.
