### ISSUE TITLE
Freedonia Error: Duplicate key './certifications/FredRamp-low.yaml' in opencontrol.yaml

### ISSUE THREAD

**Issue by METomasik** [opencontrol/compliance-masonry#332]
Using the example found here: https://github.com/opencontrol/freedonia-compliance
Using Masonry version 1.1.5 build: b3f60cb date: 2018-08-16T16:29:46+0000
No files were altered before the below command was executed.

C:\XXX\XXX\XXX\freedonia-compliance-master>compliance-masonry.exe get --verbose
2018/09/26 10:23:42 Running with verbosity
2018/09/26 10:23:42 Retrieving certifications
2018/09/26 10:23:42 Retrieving standards
2018/09/26 10:23:42 Retrieving components
2018/09/26 10:23:42 Ensuring directory C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\components exists
2018/09/26 10:23:42 Attempting to copy local resource AU_policy into C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\components\AU_policy
2018/09/26 10:23:42 Copying local resource AU_policy recursively into C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\components\AU_policy
2018/09/26 10:23:42 Retrieving dependent certifications
2018/09/26 10:23:42 Attempting to clone {https://github.com/opencontrol/freedonia-frist/ master  } into C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist
2018/09/26 10:23:42 Initializing repo https://github.com/opencontrol/freedonia-frist/ into C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist
2018/09/26 10:23:43 Cloning https://github.com/opencontrol/freedonia-frist/ into C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist
2018/09/26 10:23:45 Checking out revision master for repo https://github.com/opencontrol/freedonia-frist/
2018/09/26 10:23:47 Retrieving certifications
2018/09/26 10:23:47 Ensuring directory C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\certifications exists
2018/09/26 10:23:47 Attempting to copy local resource C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist\certifications\FredRAMP-low.yaml into C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\certifications\FredRAMP-low.yaml
2018/09/26 10:23:47 Copying local resource C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist\certifications\FredRAMP-low.yaml into C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\certifications\FredRAMP-low.yaml
2018/09/26 10:23:47 source C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist\certifications\FredRAMP-low.yaml dest C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\certifications\FredRAMP-low.yaml
2018/09/26 10:23:47 Retrieving standards
2018/09/26 10:23:47 Ensuring directory C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\standards exists
2018/09/26 10:23:47 Attempting to copy local resource C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist\standards\FRIST-800-53.yaml into C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\standards\FRIST-800-53.yaml
2018/09/26 10:23:47 Copying local resource C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist\standards\FRIST-800-53.yaml into C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\standards\FRIST-800-53.yaml
2018/09/26 10:23:47 source C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources897444847\certifications\freedonia-frist\standards\FRIST-800-53.yaml dest C:\XXX\XXX\XXX\freedonia-compliance-master\opencontrols\standards\FRIST-800-53.yaml
2018/09/26 10:23:47 Retrieving components
2018/09/26 10:23:47 Retrieving dependent certifications
2018/09/26 10:23:47 Retrieving dependent standards
2018/09/26 10:23:47 Retrieving dependent components
2018/09/26 10:23:47 Retrieving dependent standards
2018/09/26 10:23:47 Attempting to clone {https://github.com/opencontrol/freedonia-frist/ master  } into C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources023335571\standards\freedonia-frist
2018/09/26 10:23:47 Initializing repo https://github.com/opencontrol/freedonia-frist/ into C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources023335571\standards\freedonia-frist
2018/09/26 10:23:47 Cloning https://github.com/opencontrol/freedonia-frist/ into C:\XXX\XXX\AppData\Local\Temp\opencontrol-resources023335571\standards\freedonia-frist
2018/09/26 10:23:49 Checking out revision master for repo https://github.com/opencontrol/freedonia-frist/
2018/09/26 10:23:51 Retrieving certifications
ERROR: Duplicate key './certifications/FredRAMP-low.yaml' in opencontrol.yaml

**Comment by redhatrises** [comment]
Thanks @METomasik 

This issue should really be reported against `https://github.com/opencontrol/freedonia-frist/`
If you are will to submit a PR, all you should have to do is remove the `opencontrol.yaml` file from the `certifications` directory.

**Comment by METomasik** [comment]
> This issue should really be reported against `https://github.com/opencontrol/freedonia-frist/`
> If you are will to submit a PR, all you should have to do is remove the `opencontrol.yaml` file from the `certifications` directory.

Thanks @redhatrises I will do so immediately.
Unfortunately the only file in in the certifications directory is FredRAMP-low.yaml

**Comment by redhatrises** [comment]
This is most likely your problem as you have 2 `opencontrol.yaml` files that both specify `FredRAMP-low.yaml`

**Comment by METomasik** [comment]
@redhatrises is correct.

What appears to be happening is .get pulls the files down to \Temp then clones only the FredRAMP-low.yaml file to the \downloads\freedonia-compliance-master\opencontrols\certifications folder. Making it appear there is only one opencontrols.yaml file being used. Then masonry goes back to the temp folder to build the output.

Thanks for your help @redhatrises
