### ISSUE TITLE
Compliance Masonry incorrectly orders standards that end in roman numerals

### ISSUE THREAD

**Issue by riskpeep** [opencontrol/compliance-masonry#333]
If the standard and certification numbers end in roman numerals, compliance masonry will generate a document that follows natural order and thus create wrongly ordered entries in generated documents.

Consider 48 CFR 52.204-21 Basic Safeguarding of Covered Contractor Information Systems
(https://www.law.cornell.edu/cfr/text/48/52.204-21)

If we create a standard and certification that mirrors the certification, we'd have something like this:

#48CFR-52.204.21
name: 48CFR-52.204-21
standards:
  48CFR-52.204-21:
    a: {}
    b: {}
    b.1: {}
    b.1.i: {}
    b.1.ii: {}
    b.1.iii: {}
    b.1.iv: {}
    b.1.v: {}
    b.1.vi: {}
    b.1.vii: {}
    b.1.ix: {}
    b.1.x: {}
    b.1.xi: {}
    b.1.xii: {}
    b.1.xiii: {}
    b.1.xiv: {}
    b.1.xv: {}
    b.2: {}
    c: {}

The resulting document has sections ordered as follows:

[Basic Safeguards]
a: [Definitions]
b: [Requirements and Procedures]
b.1: [Basic Safeguards]
b.1.i: [Limit Access to Authorized Users]
b.1.ii: [Limit Transactions and Functions to Permitted Usage]
b.1.iii: [Limit Connections to External Systems]
b.1.iv: [Control Posted Information]
b.1.ix: [Escort Visitors and Monitor Visitor Activity]
b.1.v: [Identify Users, Processes and Devices]
b.1.vi: [Authenticate Users, Processes and Devices]
b.1.vii: [Sanitize Media]
b.1.viii: [Limit Physical Access]
b.1.x: [Monitor Internal and External Communications]
b.1.xi: [Segment Networks]
b.1.xii: [Correct Information System Flaws]
b.1.xiii: [Provide Malicious Code Protection]
b.1.xiv: [Update Malicious Code Protection]
b.1.xv: [Scan for Malicous Code]
b.2: [Other Requirements]
c: [Subcontracts]

**Note that number 9 (ix) is out of order.

Ideally the schemas for standard and/or certification would provide a 'sequence' tag that would enable authors to provide an order hint and compliance-masonry could honor it.

**Comment by riskpeep** [comment]
Thank you, I might just take that on.  My thought would be to put in an optional sequence tag rather than an roman numerals parser.  Seems a lot easier and probably more general.

**Comment by redhatrises** [comment]
> Thank you, I might just take that on. My thought would be to put in an optional sequence tag rather than an roman numerals parser. Seems a lot easier and probably more general.

That's certainly an option.... although a roman numerals parser would be more hands off for a content creator.

**Comment by redhatrises** [comment]
#334 was merged. Closing. Thanks @riskpeep
