### ISSUE TITLE
Does it work for Azure?

### ISSUE THREAD

**Issue by challs1** [opencontrol/compliance-masonry#336]

**Comment by afeld** [comment]
I assume you mean when building a system on Azure? The answer is yes. Compliance Masonry doesn't know anything about the underlying infrastructure; it just takes any compliance information in the OpenControl format and munges it together into a final deliverable.

OpenControl doesn't have anything pre-written for Azure, but you'd basically make the equivalent of https://github.com/opencontrol/aws-compliance. If you end up writing it and would be interested, happy to transfer it into the @opencontrol org!

Does that answer your question?
