### ISSUE TITLE
Consider leveraging gomodules from dep

### ISSUE THREAD

**Issue by aegershman** [opencontrol/compliance-masonry#350]
In order to keep in alignment with [`go`'s dependency management approach](https://github.com/golang/dep/commit/87f309484f0da00d4559dbe0ae5698f589f9a0d0), `compliance-masonry` should consider [leveraging gomodules](https://blog.golang.org/migrating-to-go-modules) for the dependencies used (which is quite few (which is quite nice))

Not pressing, just logging for the sake of project tracking. Thanks for folks' time 👍

**Comment by redhatrises** [comment]
Thanks for opening this.

You are right that the repo needs to be updated to support the latest gomodule instead of the legacy dep and other dependencies.
PRs are welcome.
