### ISSUE TITLE
Create a system to pick/choose components

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#48]

**Comment by afeld** [comment]
Can you elaborate on this?

**Comment by mogul** [comment]
This is intended as the first iteration toward an "SSP editor" web app which puts a pretty face on top of Compliance Masonry for people who are not very familiar with git and YAML, or want an easier editing interface... The idea is that you should be able to see a list of existing, known repositories with YAML chunks in them, say "I'm using this subset", and have it generate an `opencontrol.yaml` for you that refers to the other components. The idea was to start by having known stuff from cloud.gov like AWS, CF, and the 18F org, but then later extend that to include everything in the `FISMA Ready` organization, once each of those had YAML available.

**Comment by afeld** [comment]
I believe the editor was started in https://github.com/opencontrol/OpenControl-YAML-editor.

**Comment by mogul** [comment]
Yup, that's it... This issue belongs on that repository.

**Comment by afeld** [comment]
Issue moved to [opencontrol/OpenControl-YAML-editor #1](https://github.com/opencontrol/OpenControl-YAML-editor/issues/1) via [**ZenHub**](https://www.zenhub.com/)
