### ISSUE TITLE
Check out Spruce

### ISSUE THREAD

**Issue by dlapiduz** [opencontrol/compliance-masonry#49]
To wrangle yaml files we can use this new tool: https://blog.starkandwayne.com/2015/10/19/use-spruce-with-new-bosh-releases/

(per @joshuamckenty https://twitter.com/jmckenty/status/654337484877205504)

**Comment by afeld** [comment]
@jcscottiii Do you think this is still relevant? Possible that we could leverage it internally to take care of some of the YAML merging logic, but not sure.

**Comment by jcscottiii** [comment]
I don't think we need YAML merging right now. At the moment, we treat the YAMLs as separate but searchable objects in masonry. If ever the time comes we need it, it would be something that would be done outside the scope of masonry itself and instead in a pipeline that would come before using masonry.

**Comment by joshuamckenty** [comment]
I tried to make things work with Spruce (and Spiff) and gave up. It’s not expressive enough; hence the shift to Jinja2 templates and/or enaml-style go binaries.
