### ISSUE TITLE
Storage Change

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#90]
Currently, component yamls are stored as:
```
components/
  system/
    component.yaml
```
However, sometimes this can lead to confusion between the key and the name of the system / component. It might be better to store files like this:

```
components/
  system/
    meta.yaml
    component/
      meta.yaml
      image.png
      table.md
```
Hence the keys would be the folders and the data formally in the component.yaml files can be stored in the meta.yamls. This structure will also allow us to store images in component folders and add information to systems via the `components/system/meta.yaml`.

**Comment by Gergues** [comment]
@geramirez 
Sounds like a better design.
my 2 cents  .. 
If possible it would be better to have distinct schema  for the Component yaml vs the system yaml, 
those can map to Python classes, this way we have one place to control the schema.

For example 
components/
  system/ 
        meta.yaml ( instance of system class )
    component/
      comp-meta.yaml (instance of the component class)
      image.png
      table.md

Thanks.

**Comment by geramirez** [comment]
I like the suggestions, @Gergues. The last two weeks I've been thinking about how to refactor the code to a more OOP style. Having two separate yamls would make that easier.

**Comment by geramirez** [comment]
https://github.com/opencontrol/compliance-masonry/pull/94

**Comment by afeld** [comment]
@jcscottiii Is this still relevant?

**Comment by mogul** [comment]
I think our schema has evolved far beyond this now that we can refer to components across repositories.
