### ISSUE TITLE
DOCX renderer

### ISSUE THREAD

**Issue by Gergues** [opencontrol/compliance-masonry#93]
Currently the only render format is .md gitbook 
To build an .docx we can use the python-docx 

This library here provide a nice way to work with open xml format 
-https://python-docx.readthedocs.org/en/latest/
part of this project.
-https://github.com/python-openxml

Questions around this..
 If we are to use this library , should we fork a version for this project or build a dependency in the requirements file at setup ???

Thanks.

**Comment by geramirez** [comment]
@Gergues, You might want to fork the library for now, right now the schema is still volatile so I wouldn't want your project to break. However, we're getting close to the point where that won't be the case.

**Comment by geramirez** [comment]
@Gergues #96 is by no means complete, but it appears that reviewers are going to be more comfortable with a document format.

**Comment by Gergues** [comment]
This looks good

I had started building one but got side tracked..  This is great start and more updates will follow.

Happy holidays 🎄 to all.

-----Original Message-----

**Comment by afeld** [comment]
Now implemented! Instructions are in the README.

https://github.com/opencontrol/compliance-masonry#create-docx-template

**Comment by geramirez** [comment]
Nice this is great!
